### ISSUE TITLE
How to add elements above the pageIndicators

### ISSUE THREAD

**Issue by tysun** [ifau/SEPageViewWithNavigationBar#1]
It seems the scrollview has priority and is not allowing placement of any elements. If I add an element it just disappears. Can we add a title to the top above the pageIndicators? 

Also is it possible to get rid of the top nav bar all together so it looks clean like SnapChat? 100% UIView.

Thank you

**Comment by ifau** [comment]
Title label is placed above page indicators by default. If you want to create your own layout, you don't need add elements to scrollview directly, you need to create subclass of UICollectionViewCell and initialize it as you need. Have you seen [customization](https://github.com/ifau/SEPageViewWithNavigationBar#customization) description? I think I need to add example project..

> Also is it possible to get rid of the top nav bar all together so it looks clean like SnapChat? 100% UIView.

I didn't use SnapChat and can't understand from screenshots. Can you explain more detail, please? You want to remove left spacing, right and page indicators?

**Comment by tysunmac** [comment]
I was thinking this layout would be nice. 


I created my project with 5 VC using SEPage but it seems to skip the first VC with the title.

**Comment by tysunmac** [comment]
Sorry image doesn't show in Git message. Check this out. http://imgur.com/4Sh8zLJ

**Comment by ifau** [comment]
Looks like you don't have navigation controller or you hide navigation bar.
I just created [branch with example project](https://github.com/ifau/SEPageViewWithNavigationBar/tree/usage_example), check it out.

**Comment by tysun** [comment]
Thanks. Yes my project has the same layout. Did you see my link to the SnapChat style views with no nav bar?  Is it easy to remove that nav bar to have a clean scene? 
![4sh8zlj](https://cloud.githubusercontent.com/assets/11150198/11453253/76a9364c-95b8-11e5-95b0-1d5c43fd9711.jpg)

**Comment by ifau** [comment]
>  Is it easy to remove that nav bar to have a clean scene?

Choose root navigation controller in storyboard and uncheck "Shows navigation bar" option in attributes inspector.

**Comment by tysunmac** [comment]
Ah, that was easy. I was thinking I had to edit your swift for some reason. That's fantastic. Thank you.

**Comment by ifau** [comment]
Sorry, it is not possible, but I will add this feature. Most likely tomorrow.

**Comment by tysunmac** [comment]
ok thanks. Also I want to make the nav bar more translucent. Can I do something like this in SEPageViewWithNavigationBar.swift?

titleView.pageControl.navigationBar.translucent = true
titleView.pageControl.view.backgroundColor = UIColor.clearColor()

**Comment by tysun** [comment]
Thanks. I look forward to it.

**Comment by ifau** [comment]
I updated repository. Now you can do it by setting `bounceEnabled` property.

**Comment by tysun** [comment]
Thanks. I added the new preventBounceForScrollView function. But where do I set the bounceEnabled property?

**Comment by ifau** [comment]
You did copy source and paste from github? If so, then [look at diff](https://github.com/ifau/SEPageViewWithNavigationBar/commit/ad11ab4a95f0f8fc4698d14566b0153071b13a4d) – there is also has new property. But it is better to download file and replace the old one.

This property is `@IBInspectable`, so it will be available in attributes inspector.

**Comment by tysun** [comment]
Yes, the new property works as you said. Thanks! I'm trying to resolve the space in each scene.  When you swipe to the next screen and then swipe back the gap/space appears. I tried on iPhone 6 Plus and iPhone 5s.  
![screen](https://cloud.githubusercontent.com/assets/11150198/11482752/745909a6-9759-11e5-9cc7-8496ffa4cab7.png)

**Comment by ifau** [comment]
I just tried different layouts and they all looks as expected. I can't reproduce your problem.
Make sure, that you do not pin your views to margins (# 1), and that you do not pin they to layout guides (# 2).
![](https://cloud.githubusercontent.com/assets/3402520/11483151/fd766eaa-97b7-11e5-9a1e-bf393a96a092.png)

**Comment by tysun** [comment]
I fixed it. Pinning to layout guides is ok. The problem was really simple. I usually use aspect fit for my UIViews but in this case I had to use scale to fill. Now everything looks great. Thanks for your help. SEPage is really cool 👍🏾🦄⭐️

**Comment by ifau** [comment]
Glad to help you.
