### ISSUE TITLE
Transitions on tap ?

### ISSUE THREAD

**Issue by z00z** [ifau/SEPageViewWithNavigationBar#4]
Hello, loving this model, just wanted to see if its possible to trigger the transition when a button is tapped as well, I was experimenting with .presentViewController and the likes, the issue is when we try to present a controller which is located to the left, cause the animation always goes to the right, also the bar will be overwritten as well.

**Comment by ifau** [comment]
Hello! I don't quite understand your issue, can you explain in more details, please?
You call `presentViewController` inside one of pages, and you don't want navigation animation and overwriting navigation bar? Or something another?

**Comment by z00z** [comment]
Sorry its not really an issue, I am just wondering if it is possible to trigger the movement to page when a button is pressed, and yes I want everything to animate normally the same way that it would happen if a swipe is detected.

**Comment by ifau** [comment]
Check version from [this branch](https://github.com/ifau/SEPageViewWithNavigationBar/tree/feature/page_transitions)

You can trigger transition by next way:

``` swift
if let pageViewController = self.parentViewController?.parentViewController as? SEPageViewWithNavigationBar
{
    pageViewController.transitToNextPage()
    pageViewController.transitToPreviousPage()
    pageViewController.transitToPage(atIndex: 0)
}
```

It's a little ugly because of view controllers hierarchy. Maybe I will think later how to make interface more friendly.

**Comment by z00z** [comment]
I managed to do it like so

```
 self.pageViewController.setViewControllers([contentViewControllerToDisplay], direction: direction, animated: true, completion: nil)
self.currentPage = indexPath.row

```

**Comment by ifau** [comment]
I don't understand your comment. Are you want to place button inside one of child controller that will trigger transition to another child controller, like this? If so, then the solution is above.

![](https://cloud.githubusercontent.com/assets/3402520/18768090/f82fb56c-8133-11e6-8b17-cd8128e14be9.gif)

**Comment by z00z** [comment]
Yeah that was my question, I managed to do it using the code I posted there as well.

Thanks for your help :)
